### ISSUE TITLE
[Bug] - Nested placeholder handles unproperly

### ISSUE THREAD

**Issue by Speik** [ruViolence/GraalJS-Expansion#2]
### When I'm trying to pass nested placeholder, it doesn't work.

For example:
`%graaljs_util_format_date_{player_first_join_date},DD.MM.YYYY HH:mm:ss%` returns `empty string` and execution doesn't even begins - this could be checked easily by typing simple `print` at first line of `onPlaceholderRequest` function.

**But!** During my experiments I've investigated that problem is not in curly brackets - problem is in underscores. So if I'll try something like this `%graaljs_util_format_date_{player#first#join#date},DD.MM.YYYY HH:mm:ss%`, execution will start and as first argument I got expected value `{player#first#join#date}`.

Purpur 1632 (1.18.2)
PlaceholderAPI 2.11.2
GraalJS Expansion 1.1.2

**Comment by ruViolence** [comment]
Nested placeholders are not supported. If you want to use them, you need to do it inside the script, like this:
```js
bukkitClassLoader.loadClass("me.clip.placeholderapi.PlaceholderAPI").static.setPlaceholders(player, "%player_first_join_date%");
```

**Comment by Speik** [comment]
> Nested placeholders are not supported. If you want to use them, you need to do it inside the script, like this:
> 
> ```js
> bukkitClassLoader.loadClass("me.clip.placeholderapi.PlaceholderAPI").static.setPlaceholders(player, "%player_first_join_date%");
> ```

I understand that I can use PAPI `setPlaceholders`, but the issue is - any text passed as argument, **separated by underscores** (even simple text, or block identifier, for example) breaks placeholder execution and parsing, nothing happens

**Comment by ruViolence** [comment]
Finally got my hands on it. Try the [latest version](https://github.com/ruViolence/GraalJS-Expansion/releases/tag/v1.2.0), the separator of the script name and the arguments enumeration is now the `#` symbol. So now you have to use the following construction: `%graaljs_some_script#args%` The `#` symbol can also be used in arguments, since only the first such symbol is checked.
